{{- if and .Values.trigger.enabled .Values.trigger.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.trigger.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kagents
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: trigger
{{- end }}
